### PR TITLE
Textmix

### PR DESCRIPTION
**Pull request by uperetz**
This is the code, some commits probably need squashing, but for now I leave the branch expanded.

### CODE REVIEW

**Comment by uperetz** [comment]
Main things I'd like comments on:

1. Are the methods spread across in a manner you deem logical?
2. A better way (in the render attribute probably) to render plain text, rather than all the string replacements (which I'm not even sure is compatible with everything).
3. What key should I use to enter math mode? I don't want to waste !, that's temporary.
4. Anything else you think I should improve add :)

**Comment by daniel3735928559** [comment]
Thanks for the PR.  This will take a little time to think through--more than I have at the moment--but some quick thoughts (a bit in the spirit of "I did not have time to write a short letter so I wrote a long one instead"): 

* The button GUI is definitely progress along the right track.  There should be some grouping of symbols by type (e.g. a tab in the GUI for Greek letters), and so there should probably be metadata in the symbol definitions themselves to help in making this grouping automatic.  The ultimate use-case for that would be as the sole interface to the editor on mobile, so it would have to be usable enough for that.

* After playing with it, I think the text+maths combo input gets away from what I'm trying to support.  There is already a method to enter text alongside maths using the "text" symbol, and the point is that the editor be a standalone maths-only widget that could perhaps integrate into a broader text editor.  See, for instance, [http://daniel3735928559.github.io/kit/](http://daniel3735928559.github.io/kit/) for an (old, somewhat broken) example of integrating the editor into CodeMirror (press "edit" to open the editor, and then use Alt+Shift+m while editing to insert a Guppy instance).  I would be interesting in hearing about what use-case led you down this road, however.  

* The refactoring is a helpful step away from the current monolithic mess.  It makes the code easier to read, but it doesn't make the pieces stand alone as they will need to in future--e.g. transform.js still references the one global Guppy object.  In the end, I think the needs of future work are going to require a kind of OOP-like rethinking; something like: There are "Guppy documents" and methods for modifying them (`insert_symbol`, `make_e`, etc.), there is the "Guppy document renderer" which is a standalone piece that consumes "Guppy documents" and turns them into whatever--LaTeX, serialised XML, etc., and there is the "Guppy interface", which turns inputs (keypresses, mouse buttons, etc.) into calls to the "Guppy document" API, and which draws itself by passing the "Guppy document" object to the "Guppy document renderer" to generate LaTeX, which it passes on to KaTeX for drawing.  This division of labour would allow, for example, someone to create a different frontend for the editor while not having to recreate the method for storing the expressions, and would create an easy solution to #55.  

Based on these thoughts, my initial reaction would be: 

* Break the PR into separate PRs for the three pieces.  

* Remove or at least isolate the changes relating to the text+maths feature.  Unless there really is a compelling general need for it, this would probably best be left as part of a fork (or maybe a plugin, if this project ever gets far enough to warrant a plugin system).

* Ensure in particular that the GUI is a relatively modular/separable piece of code (as it is the way you've done it now) in its own PR and I'll be willing to do some extra work to help pull that in.  

Generally, this PR touches on several issues I'll want to consider carefully in the next sprint on this project.  The GUI is more standalone so I'm comfortable trying to merge that now.  The refactoring does genuinely make the code more pleasant than it was before, but it has ramifications that will take some time to think through, so I'm inclined to wait until I can allocate that time.

**Comment by uperetz** [comment]
Thanks I'll think about factoring as well. If I continue work, it will be
GUI only. Note the way i made it is one GUI is enough per page, with
auto-detection of active guppy.

Let's talk when you think you know how you want to proceed. Depending on
how you want the final factoring to be, I'll consider the textmix again.
I'll be direct here, I want better than Moodle behavior for input on new
questions to a system:

   - Regular text would need support in this case. The new text cannot
   (should not rather) be passed along to katex to support spacing and line
   breaks and for speed reasons, beyond looking normal rather than math. It is
   not 'conceptually' a symbol. Rather the text symbol is obsolete I would say.
   - The way it currently is I think is OK, but after some deliberation I
   think a better solution would be to reverse the role of the T node to 'pure
   text' rather than the math part.  That way the "pure katex" mode would
   remain identical without an extra T layer, and T would actually stand for
   text. With a default of true on pure katex this would essentially be a
   completely invisible option, and detaching it from the rendering function
   is simple enough.
   - Continuing along that thought and your nice factor suggestions, while
   "add_classes_cursors" would still need to be able to process this, maybe
   attaching rendering as a node property is the way to go here, and more
   OOPish.

Like I said, I will do nothing until you decide how you're proceeding.
Another thing I think should be available is an automatic 'done' function
(as an option)  that will add a line break, essentially for inputting
equations below each on the same div. This is useful for me and I think
will be in general. I was thinking either:

   - Just plain ol'e <br/>. Deletion would have to account for it. I could
   do this easily as text-mix is implemented, but maybe it will changing.
   - Feeding katex a matrix to render. I'm having problems with matrix
   currently, so I'll have to see.

Again, I will currently do no work on these until you decide how code
should look like, and I'd be happy to discuss this with you. Regarding the
GUI, the key feature currently is auto-loading of symbols and the fact only
one is needed for multiple guppy fields (which I'm working on). In fact, I
should probably enforce this, though we don't have to. I think next I'll
add styling when I get around to it, specifically sub-menus as you suggest
and a search bar.

Let's talk more when you have a picture of the module tree.

**Comment by daniel3735928559** [comment]
Hey--finally circling back around to this.  If you're still available/up for working this, I've got a plan for going forward at last.  If not, no worries as I can pull in items from the code you've already written, since it's pretty well organised.

* Re: Refactoring: I think I have settled on a reasonable refactoring plan that accomplishes what I need, expressed in #58.  It's a little coarser than what you did, but, I think, conceptual.  I'm open to feedback, however.

* Re: Text entry: The business of creating actual mathematical documents (such as Moodle questions) is definitely the ultimate goal, and I do think there is a case to be made that Guppy could be useful there--e.g. if a teacher wants to be able to search for questions with certain elements (say "find questions involving derivatives and quotients with polynomial denominators") that could be aided by having the mathematical expressions themselves stored in a structured way.  

  However, I'd like to avoid going down the road of recreating all the classic text editor features in Guppy proper.  Documents (including homework questions) will eventually also want bold text, paragraph breaks, embedded images, graphs, and so on, and most of those are well outside the scope of this project.  So rather, I would guess that the best way to proceed would be to leave Guppy as a pure equation editor and integrate it with an existing rich text editor.  I've already done some work integrating it with CodeMirror (see [kit](https://github.com/daniel3735928559/kit)), but one could imagine writing a Guppy plugin for Quill (see [quilljs.com](https://quilljs.com)), which seems in general like a good fit for Moodle.  

* Re: GUI.  This is a great start.  I'd be very happy to merge a PR with just the GUI code, and I can work that into the refactoring.  I've not got to try it on a phone, which is the primary situation I'm concerned about, but this is miles better than the nothing that I currently have.

**Comment by daniel3735928559** [comment]
I've done the refactoring and GUI implementation now.  I'm still disinclined to move on the integration of text entry, so I'll close this for now.  Thanks again!

**Pull request closed without merging**
